### PR TITLE
fix yarn when running inside winpty

### LINKED ISSUE #627: [4.0.0 | Git Bash | Windows 10] stdin is not a tty
Husky 4.0.0 isn't working in Git Bash for Windows 10, triggering a `stdin is not a tty` error for every git operation that triggers a hook.

#### Versions

OS: Windows 10 1903
Shell: Git Bash (`GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)`)
Git: `git 2.24.1.windows.2`

#### `HUSKY_DEBUG=1 npm install husky --save-dev`

```
$ HUSKY_DEBUG=1 npm install husky --save-dev

> husky@4.0.0 install C:\dev\test\husky4-tty-test\node_modules\husky
> node husky install

husky > Setting up git hooks
husky:debug Current working directory is C:\dev\test\husky4-tty-test\node_modules\husky
husky:debug INIT_CWD is set to C:\dev\test\husky4-tty-test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: undefined
husky:debug   --show-prefix:
The "path" argument must be of type string. Received type undefined
husky:debug TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:139:9)
    at getDirs (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:27:49)
    at run (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:62:62)
    at Object.<anonymous> (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
husky > Failed to install

> husky@4.0.0 postinstall C:\dev\test\husky4-tty-test\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN husky4-tty-test@1.0.0 No description
npm WARN husky4-tty-test@1.0.0 No repository field.

+ husky@4.0.0
added 48 packages from 22 contributors and audited 48 packages in 2.047s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

#### `HUSKY_DEBUG=1 git commit`

Note: on the fresh test repo, this command worked because the first command failed so the hooks did not install properly. On an existing repo with existing hooks, it looks like this:

```
husky:debug husky v4.0.0 (created at 1/7/2020, 1:24:18 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is /c/dev/test/existing-repo
husky:debug pre-commit hook started
stdin is not a tty
husky:debug yarn husky-run exited with 1 exit code
```

### PR DESCRIPTION
**Pull request by casz**
see https://github.com/yarnpkg/yarn/issues/2998#issuecomment-351424672

fixes #627 
fixes #635

### CODE REVIEW

**Comment by casz** [comment]
This issue won't exist in https://github.com/yarnpkg/berry

This is only related to yarn v1

**Comment by casz** [comment]
Not sure if we should add some sort of conditional logic to the getScript's render function based on version of yarn.

**Comment by arcanis** [comment]
> I also question the need for specifically running with `yarn`.

No, you must use `yarn run` if the packages are installed with Yarn. Npx has no idea about the mechanisms we use to layout the files, which are bound to differ.

> Not sure if we should add some sort of conditional logic to the getScript's render function based on version of yarn.

At the very least I think you should add a check for Yarn 1 vs Yarn 2 (but only when `winpty` is in the environment), as `--no-interactive` isn't a valid option in Yarn 2 (and it doesn't silently accept invalid options anymore).

**Comment by casz** [comment]
As I suspected @arcanis :)

**Comment by casz** [comment]
Since yarn v2 is the only one with pnp?

would it make sense for yarn v1 to use npx?
or do you want me to do the winpty dance?

**Comment by arcanis** [comment]
I wouldn't recommend using `npx` for Yarn. I don't control this package and I can't ensure that it'll stay compatible with us. For all we know maybe npm will one day want to make their own install processes that will be incompatible with `node_modules`. It also looks fairly unmaintained so ... 🤷‍♀️

**Comment by casz** [comment]
I reverted lots of the changes and made it use a simpler approch

**Pull request merged**
