### PR TITLE
Add HUSKY_SKIP_HOOKS env var to skip running hooks

### PR DESCRIPTION
**Pull request by ozzywalsh**
Requested in #487.

This adds support for a  `HUSK_SKIP_HOOKS` environment variable. When this is set to `1` or `true`, husky skips running the hooks.

### CODE REVIEW

**Comment by ozzywalsh** [comment]
I have added a test to the `.travis.yml`.

Any feedback or comments is appreciated.

**Comment by ozzywalsh** [comment]
Next thing I shall do is push some documentation.

**Comment by ozzywalsh** [comment]
All done.

Would appreciate your input @typicode

**Comment by typicode** [comment]
Thanks for the PR :)

**Comment by tomratcliffe** [comment]
FYI I think this also closes https://github.com/typicode/husky/issues/346? Nice work! :+1:

**Comment by typicode** [comment]
@tomratcliffe yes :+1:

**Pull request merged**
