### PR TITLE
use npx when package manager is yarn

### LINKED ISSUE #627: [4.0.0 | Git Bash | Windows 10] stdin is not a tty
Husky 4.0.0 isn't working in Git Bash for Windows 10, triggering a `stdin is not a tty` error for every git operation that triggers a hook.

#### Versions

OS: Windows 10 1903
Shell: Git Bash (`GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)`)
Git: `git 2.24.1.windows.2`

#### `HUSKY_DEBUG=1 npm install husky --save-dev`

```
$ HUSKY_DEBUG=1 npm install husky --save-dev

> husky@4.0.0 install C:\dev\test\husky4-tty-test\node_modules\husky
> node husky install

husky > Setting up git hooks
husky:debug Current working directory is C:\dev\test\husky4-tty-test\node_modules\husky
husky:debug INIT_CWD is set to C:\dev\test\husky4-tty-test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: undefined
husky:debug   --show-prefix:
The "path" argument must be of type string. Received type undefined
husky:debug TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:139:9)
    at getDirs (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:27:49)
    at run (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:62:62)
    at Object.<anonymous> (C:\dev\test\husky4-tty-test\node_modules\husky\lib\installer\bin.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
husky > Failed to install

> husky@4.0.0 postinstall C:\dev\test\husky4-tty-test\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN husky4-tty-test@1.0.0 No description
npm WARN husky4-tty-test@1.0.0 No repository field.

+ husky@4.0.0
added 48 packages from 22 contributors and audited 48 packages in 2.047s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

#### `HUSKY_DEBUG=1 git commit`

Note: on the fresh test repo, this command worked because the first command failed so the hooks did not install properly. On an existing repo with existing hooks, it looks like this:

```
husky:debug husky v4.0.0 (created at 1/7/2020, 1:24:18 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is /c/dev/test/existing-repo
husky:debug pre-commit hook started
stdin is not a tty
husky:debug yarn husky-run exited with 1 exit code
```

### PR DESCRIPTION
**Pull request by casz**
alternative to #634 

fixes #634 
fixes #627

### CODE REVIEW

**Comment by typicode** [comment]
Yarn 2 has a new Plug'n'Play features which installs modules in a single `pnp.js` file and not in `node_modules` anymore. From what I understand, to be able to run `husky-run` bin, the package manager needs to be Yarn.

So I don't think that in this context, `npx --no-install husky-run ...` will work.

https://next.yarnpkg.com/features/pnp

**Comment by arcanis** [comment]
Yep, exactly 👍

**Comment by casz** [comment]
That's fine cannot be aware of all the context :)

**Comment by aminya** [comment]
Can we have npx for npm too? It will probably fix https://github.com/typicode/husky/issues/673 and https://github.com/conventional-changelog/commitlint/issues/1665

**Pull request closed without merging**
