### PR TITLE
Fix: Create .git/hooks if doesn't exist

### PR DESCRIPTION
**Pull request by luiscoms**

### CODE REVIEW

**Comment by lmachens** [comment]
Is this related to https://github.com/conventional-changelog/standard-version/issues/254?

**Comment by luiscoms** [comment]
Nice, it is ready to merge

**Comment by luiscoms** [comment]
> Is this related to [conventional-changelog/standard-version#254](https://github.com/conventional-changelog/standard-version/issues/254)?

Yes, if directory does not exists, create it

**Comment by typicode** [comment]
@luiscoms Thank you for the PR :+1:  (I wanted to wait to release `1.0`  before, but now that's it's done :))

**Comment by typicode** [comment]
Hmm, I didn't merge to the right branch (should have changed to `master`) :/
Not sure how to fix that and keep your name associated to the changes.

Would you mind recreating a PR? Or if you prefer/don't have the time I can pick the code and mention @ you in the commit description?

**Pull request merged**
