### PR TITLE
Mercurial support

### PR DESCRIPTION
**Pull request by tobiastimm**
Hi folks,

I really love working with `husky` in my `git` repositories. At work unfortunately, we are using Mercurial as a VCS. I didnt' find anything comparable to `husky` in hg, so i thought i would add `hg` support to `husky`.

The pull request isn't in final state, opinions and suggestions are appreciated.

Things to do:

- [x] proper detection for existing hg hooks
- [x] reverting changes in hgrc on uninstall

Consider to implement in the future:
- [ ] bypass hooks (hg has no --no-verify or built-in option to do that, also hg doesn't support custom options in the cli)
- [ ] hg subrepos support

### CODE REVIEW

**Comment by TobiasTimm** [comment]
@typicode if you are interested in this, i could try to develop it against the `beta` branch.

**Comment by alexeyten** [comment]
Can't say for typicode, but I'm not a fan of changing project code style.

The idea is still great though.

**Comment by TobiasTimm** [comment]
@alexeyten i can revert the code style changes. Happend by accident thx to my prettier & eslint extension in vscode :smile:

**Comment by TobiasTimm** [comment]
At work we've tested my hg support and it works perfect for us. Would be glad about some feedback, if this feature could be merged into husky?

**Comment by mdxs** [comment]
Would like to see this one day... Unfortunately, due to inexperience with node/npm cannot commit to test it; just want to use it within a hg project inspired by a git project that uses it.

**Comment by TobiasTimm** [comment]
@vyshkant I've created my own package, because I haven't received any answer at all, yet. https://github.com/TobiasTimm/husky-hg

**Comment by Brianzchen** [comment]
Does husky support `hg` yet? I can't find any reference to it outside of this issue in this repo

**Pull request closed without merging**
