### PR TITLE
added HUSKY_SKIP_INSTALL env variable to skip hook install

### LINKED ISSUE #172: env variable to prevent install
Hi,
Can we add an env variable to disable the install script?
something like the CI detection.

Let me know if I should open a PR.
Thanks

### PR DESCRIPTION
**Pull request by noamokman**
Hi,

This closes #172.
Let me know if I need to change something.

Thanks!

### CODE REVIEW

**Comment by agconti** [comment]
@noamokman thanks for making this PR!

**Comment by typicode** [comment]
Thank you :+1:

**Comment by satazor** [comment]
@typicode Could we have a release on the 0.14.x line with this change? Thank you.

**Comment by szimek** [comment]
I had no idea that such option is present, so I just added `husky` to `optionalDependencies` - this way `yarn/npm install` won't fail if installing `husky` fails. Probably not as good as built-in option, but solves the problem for people still on 0.14.x.

**Pull request merged**
