### PR TITLE
Replace `execa` with  git bash

### PR DESCRIPTION
**Pull request by gucong3000**
- Run commands using Git bash as shell (for Windows)
- Run commands using posix shelll (for other OS)
- Remove `execa` from deps and enhance Cross-platform features

### CODE REVIEW

**Comment by gucong3000** [comment]
Is there anything I can do for help this PR ?

**Comment by deecewan** [comment]
i'm not sure why you can't do this with execa?

**Comment by gucong3000** [comment]
> i'm not sure why you can't do this with execa?
execa not support bash script like:
```shell
eslint $(git ls-files | grep \.js$)
```

**Comment by gucong3000** [comment]
@deecewan
Hi, I reduced the dependency project

**Comment by typicode** [comment]
Closing, see https://github.com/typicode/husky/pull/590
Thanks a lot for the PR!

**Pull request closed without merging**
