### PR TITLE
Fixing javascript linting with semicolons

### PR DESCRIPTION
**Pull request by lirantal**

### CODE REVIEW

**Comment by typicode** [comment]
Hi @lirantal,

Thank you for the PR, I know there's debate about putting or not semicolons. But personally, I prefer to omit them.

**Comment by lirantal** [comment]
Interesting. Why do you prefer to omit them?

**Comment by typicode** [comment]
For me, it's more readable this way :)

**Comment by lirantal** [comment]
Well someone's picky, eh? :)

**Comment by iamstarkov** [comment]
@lirantal i looked into the code and didnt found any linter configs there. what linting errors have you fixed?

**Comment by lirantal** [comment]
I was referring to a local linting setup I have in my IDE

**Pull request closed without merging**
