### PR TITLE
docs: update install script to mjs and fix CI checks

### LINKED ISSUE #1356: Cannot run CI compatible install script
The installation scripts compatible with CI need to be modified for these reasons.

### Must indicate ES Modules because it uses top-level await

``` bash
PS C:path\to\directory> npm i

> directory@1.0.0 prepare
> node .husky/install.js

C:path\to\directory\.husky\install.js:5
const husky = await import('husky')
              ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at internalCompileFunction (node:internal/vm:77:18)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.0
npm ERR! code 1
npm ERR! path C:\path\to\directory
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node .husky/install.js
```

### `husky()` is not a function, so it must use `husky.default()`

``` bash
PS C:path\to\directory> npm i

> directory@1.0.0 prepare
> node .husky/install.mjs
file:///C:/path/to/directory/.husky/install.mjs:6
husky()
^

TypeError: husky is not a function
    at file:///C:/path/to/directory/.husky/install.mjs:6:1

Node.js v20.11.0
npm ERR! code 1
npm ERR! path C:path\to\directory
npm ERR! command failed

```

### CI checks should be fixed
According to ci-info, when we use `process.env.CI`, we should use `!!(process.env.CI !== 'false' && process.env.CI)`.

https://github.com/watson/ci-info/blob/v4.0.0/index.js#L56-L69

### PR DESCRIPTION
**Pull request by starnayuta**
close #1356

### CODE REVIEW

**Comment by typicode** [comment]
Thank you for the PR. You're right about the CI check. However I prefer easy-to-understand code, and it should be compatible with most CIs, especially GitHub Actions.

Using `.mjs` is a better choice :+1: . I've simplified the code too. There's actually no need for `await`.

**Comment by starnayuta** [comment]
Okay, I see what you're thinking.

How about changing `process.env.CI === '1'` to `process.env.CI === 'true'`?

GitHub Actions is also set to true.  
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

**Comment by typicode** [comment]
Good catch, I thought for GitHub Actions it was 1.

**Comment by starnayuta** [comment]
If you run import without husky installed, `Cannot find package ‘husky’` error will occur.

https://github.com/typicode/husky/blob/main/docs/how-to.md?plain=1#L73

**Pull request merged**
