### PR TITLE
fix: make husky work with pnpm

### LINKED ISSUE #61: Installation with pnpm doesn't setup the hooks
Hi there, are you planning to support `pnpm` installation?

### PR DESCRIPTION
**Pull request by zkochan**
Close #61

### CODE REVIEW

**Comment by zkochan** [comment]
There seem to be an error in master, that is why CI fails

**Comment by zkochan** [comment]
@typicode could you have a look on this, please?

**Comment by typicode** [comment]
Hi @zkochan,

Thank you for the PR! I’m working on a new version which should support pnpm. There’s no branch yet though.

**Comment by typicode** [comment]
Closing as it's fixed in beta
https://github.com/typicode/husky/tree/dev

**Pull request closed without merging**
