### PR TITLE
Optionally overwrite existing hooks

### LINKED ISSUE #336: Propose: make husky-install configurable when git-hooks have already exists
In my scene:
I already have `commit-msg` hook, so running `npm i husky -D` fails to inject husky's `commit-msg` hook.

so I consider that I could make husky-install configurable. For example:

- `package.json`
```json
{
  "husky": {
     "installType": "overwrite"
  }
}
```

And husky could read `install` field which is one of `overwrite`, `append`, `skip(by default for compatibility)`.

- `overwrite`: overwriting the previous hook
- `append`: appending to the previous hook
- `skip`: skipping husky

### PR DESCRIPTION
**Pull request by tomasbjerre**
# Problem

I'm working within an organization where we get Git Bash pre packaged with hooks. We cannot change that and every developer will get these hooks, from the installation of Git Bash, installed when cloning repositories. The pre packaged hooks will make Husky ignore any hooks configured in `package.json`.

Developers must do something like:
```shell
git clone whatever.git
rm ./git/hooks/*
npm install
```

# Solution

Adding a configuration option (`overwriteExisting`) to `package.json` like:
```json
...
"skipCI": true,
"overwriteExisting": true
"pre-commit": ...
``` 

With `overwriteExisting` as `true` in the configuration it will overwrite any existing hook on `npm install`.

Fixes #336 and #558

### CODE REVIEW

**Comment by tomasbjerre** [comment]
@OlofFredriksson

**Comment by jsumners** [comment]
Very nice. I hope this gets accepted.

**Comment by tomasbjerre** [comment]
Would also be nice to get https://github.com/typicode/husky/pull/204 merged so that only configured hooks are overwritten.

**Comment by jsumners** [comment]
Could someone from the project team at least chime in as to the acceptability of this? @typicode seems to be the most active committer so tagging.

**Comment by aviaryan** [comment]
Sorry for the ping but would really appreciate this getting merged. @typicode Please look into this. Thank you.

**Comment by casz** [comment]
Now with the new `. "$(dirname "$0")/husky.sh"` in all the hooks this should be fairly simple to look if `pre-commit` has `. "$(dirname "$0")/husky.sh"`

**Comment by cm0s** [comment]
Nothing new about this PR?

**Comment by tomasbjerre** [comment]
We created out own workaround, a tool that runs on `prepare` in `package.json`. It is internal to my employer so I cannot share it.

But! I started fiddling with a more general solution. I created a concept with [dictators](https://github.com/tomasbjerre/dictator-builder) that share functionality in a [dictator-builder](https://github.com/tomasbjerre/dictator-builder).

The idea is to add it in repositories by adding this to `package.json`:
```
  "scripts": {
    "prepare": "npx haffaz@0.0.13"
  }
```

And [dictators](https://github.com/tomasbjerre/dictator-builder) helps build dictators by reading configuration from dictators, like:

```json
{
  "message": "Setup some git stuff.",
  "actions": [
    {
      "copyFrom": "pre-commit-hook.txt",
      "target": ".git/hooks/pre-commit",
      "chmod": "0755"
    },
    {
      "copyFrom": "gitmessage.txt",
      "target": ".gitmessage"
    },
    {
      "target": ".gitignore",
      "haveLineContaining": [".gitmessage"]
    }
  ]
}
```

It allows us to create one tool that setup commit-linting as well as all other static code analysis and other files that else are duplicated in all repositories.

**Comment by yinzara** [comment]
Any love on this?

**Comment by typicode** [comment]
Thanks for the PR. Closing as v5 won't have this problem.

**Comment by jsumners** [comment]
@typicode can you link to a PR or documentation describing the resolution?

**Pull request closed without merging**
