### PR TITLE
chore: clean-up code base

### PR DESCRIPTION
**Pull request by paescuj**
First of all, thank you very much for providing and maintaining `husky` ❤️ 

While working on another pull request I realized that there are currently some lint issues (popping up in VS Code). So I decided to fix them and take the chance to give the whole code base a little clean-up:
* **Linting**
  * Fix indentation errors from ESLint
  * Add lint step to `pre-commit` and GitHub workflow
* **GitHub workflows**
  * Use more appropriate naming for jobs
  * Consolidate `test` jobs into one by using the matrix `exclude` option for Windows with Node.js 14
* **[`husky.sh`](https://github.com/typicode/husky/compare/main...paescuj:husky:chore/clean-up-code-base?expand=1#diff-b4a2bcefec96fd2e133fdc0c0817c76f881b789553b069896e48e74e46b6fc5d) shell script**
  * Apply recommendations from `shellcheck`, inspired by #1226 
* **TypeScript files**
  * Convert comments on functions and variables to JSDoc, so we profit from the descriptions in IDEs
  * Add / enhance some comments
* **`test` shell scripts**
  * Apply recommendations from `shellcheck`
  * Unset `GIT_INDEX_FILE` env var when called via git hook, that is running `git commit` in this very repo.
     Otherwise git commands in tests are running into conflicts because they are using the index from this repo instead of the temporary test repos. Honestly, I'm a bit surprised this hasn't been an issue for others before...
   * Use `printf` instead of `echo -e` for true POSIX (for example, special chars were printed instead of colored output on macOS)
* **[`tsconfig.js`](https://github.com/typicode/husky/compare/main...paescuj:husky:chore/clean-up-code-base?expand=1#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0) file**
  * Expand from `node14` config since we're targeting Node.js >=14
* **[`CONTRIBUTING.md`](https://github.com/typicode/husky/compare/main...paescuj:husky:chore/clean-up-code-base?expand=1#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) file**
  * Fix reference to LICENSE file

### CODE REVIEW

**Comment by typicode** [comment]
Thank you, I'll review it with other PRs for the next major release (planned for the end of life of Node 14).

**Comment by paescuj** [comment]
> Thanks again for the PR 👍 I may not merge everything so I'm splitting it into smaller PRs and adding you as co-author for attribution.

What's wrong with the other changes?
Should we close this PR now?

**Comment by typicode** [comment]
Nothing wrong, mostly personal taste (for example, not sure if I want to add shellcheck style and I prefer `//` style for comments in JS).
Also changelog will maybe be generated, with multiple PRs it's clearer/more readable.

I'm keeping this PR open for reference, I'll close it later :)

**Comment by paescuj** [comment]
I see, thanks for letting me know! 👍

**Pull request closed without merging**
