### PR TITLE
Add simplified Chinese documentation

### PR DESCRIPTION
**Pull request by CosmoLau**
* Add simplified Chinese documentation
* Update vitepress to version 1.0.0-bete.6

### CODE REVIEW

**Comment by zqy233** [comment]
老铁，有空给你的仓库整下github pages，让我先用上，哈哈

**Comment by CosmoLau** [comment]
> 老铁，有空给你的仓库整下github pages，让我先用上，哈哈

我是机翻+润色的，可以看看哪些地方翻译的有问题，提个PR，用的话随便用，我有 github pages，只是没挂上去

**Comment by CosmoLau** [comment]
> 老铁，有空给你的仓库整下github pages，让我先用上，哈哈

github pages 部署好了

[https://www.cosmolau.top/docs/husky/zh/](url)

**Comment by zqy233** [comment]
> > 老铁，有空给你的仓库整下github pages，让我先用上，哈哈
> 
> github pages 部署好了
> 
> https://www.cosmolau.top/docs/husky/zh/

优秀啊

**Comment by SCWR** [comment]
@typicode Is there a possibility to merge this request?

**Comment by typicode** [comment]
Sorry for the delay. I'll merge it so that it's available for people using v8.
However, I'm not sure I have the bandwith to manage/maintain multiple languages.

**Pull request merged**
