### PR TITLE
refactor: rename files

### PR DESCRIPTION
**Pull request by typicode**

### CODE REVIEW

**Comment by mrkjdy** [comment]
I believe this broke imports of this package. Now I'm getting this TypeScript error:
image

`index.d.ts` needs to be renamed to `index.d.mts` as well

**Comment by typicode** [comment]
Thanks do you want to make a PR?

**Comment by glensc** [comment]
care to explain why the rename is necessary? what does it do (improve?, fix?)

**Comment by typicode** [comment]
> care to explain why the rename is necessary? what does it do (improve?, fix?)

It simplifies package.json. For a tiny project like this, I felt it would be better.

It's not necessary by any means but mostly a preference.

**Pull request merged**
