### PR TITLE
[enhancement] Custom npm binary/script 

### PR DESCRIPTION
**Pull request by valorize**
be able to source a huskyrc file and specify npm script path in there

### CODE REVIEW

**Comment by fcarreiro** [comment]
Great! Could you also add some docs? I'm not sure where it should go... README?

**Comment by valorize** [comment]
Done :)

**Comment by iGitScor** [comment]
Hi,

This perfectly fits my need, thank you!

Does it could be a config in the `package.json` too ?

Thank you

**Comment by valorize** [comment]
@iGitScor One would have to parse the package.json file in the bash script. Doable with something like
```
NPMPATH=`grep '"npmPath"' package.json | sed -e 's#"npmPath"\s*:\s*"\(.*\)"'`
```

**Comment by errorx666** [comment]
I need this feature.  The PR has been open for several months - what's holding this up?

**Comment by valorize** [comment]
¯\_(ツ)_/¯
maybe because all tests are failing

**Comment by dawidnawrot** [comment]
> Regarding huskyrc or package.json config, it's possible now thanks to cosmiconfig.

@typicode could you provide an example of how to use external node engine using cosmiconfig and husky?

**Comment by dawidnawrot** [comment]
@typicode So, does the code from closed PR is refactored and merged with newest husky version? If so, how can we define node engine? There's not a word about it in docs.

**Pull request closed without merging**
